# Default values for .helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: oai-ric-test
service:
  name: flexric
  port: 36421
  type: NodePort
  node_port: {{ requiredEnv "NODE_PORT" }}
image:
  repository: {{ requiredEnv "REPO_URL" }}
  tag: {{ requiredEnv "IMAGE_NAME" }}
configmap_data:
  flexric_conf: |-
    [NEAR-RIC]
    NEAR_RIC_IP = 0.0.0.0

    [XAPP]
    DB_DIR = /tmp/